name: CI
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - master
jobs:
  test:
    # Job name is Test
    name: Test
    # This job runs on macOS
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=13.5,name=iPhone 8']
        xcode: ['/Applications/Xcode_11.5.app/Contents/Developer']
    steps:
      - name: Build and test
        run: bundle exec fastlane scan
      - name: Archive Failed Tests artifacts
        if: failure()
        uses: actions/upload-artifact@v1
        with:
          name: FailureDiff
          path: checkout/FailureDiffs
